name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: |
          rsync -avvz --delete \
            -e "ssh -p ${{ secrets.SERVER_PORT }}" \
            --exclude '.git*' \
            --exclude 'data' \
            --exclude '.env' \
            --exclude 'docker-compose.yml' \
            ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/www/dk_project/dk_app/onenav_dev/
      
      - name: Fix permissions and verify deployment
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "
            # 修复权限
            sudo chown -R www-data:www-data /www/dk_project/dk_app/onenav/onenav_nz8t/onenav_dev/
            sudo chmod -R 755 /www/dk_project/dk_app/onenav/onenav_nz8t/onenav_dev/
            
            # 验证文件存在
            if [ ! -f /www/dk_project/dk_app/onenav/onenav_nz8t/onenav_dev/index.php ]; then
              echo 'Error: index.php not found!'
              exit 1
            fi
            
            # 重启容器
            cd /www/dk_project/dk_app/onenav/onenav_nz8t
            docker-compose down
            docker-compose up -d
          "