name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Debug SSH connection
        run: |
          ssh -v -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "pwd"
      
      - name: Deploy with rsync
        run: |
          rsync -avvz --delete \
            -e "ssh -p ${{ secrets.SERVER_PORT }}" \
            --exclude '.git*' \
            --exclude 'data' \
            ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/www/dk_project/dk_app/onenav_dev/
      
      - name: Set permissions
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "
            chmod -R 755 /www/dk_project/dk_app/onenav_dev/
            chown -R www-data:www-data /www/dk_project/dk_app/onenav_dev/
          "